export default {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-css-modules',
    'stylelint-config-standard',
    'stylelint-config-standard-scss',
  ],
  plugins: ['stylelint-order', 'stylelint-scss'],
  rules: {
    'no-empty-source': null,
    'color-hex-length': 'short',
    'order/order': [['custom-properties', 'declarations'], { unspecified: 'bottom' }],
    'order/properties-order': [
      [
        'display',
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'flex',
        'flex-grow',
        'flex-shrink',
        'flex-basis',
        'align-items',
        'justify-content',
        'width',
        'height',
        'margin',
        'padding',
        'background',
        'color',
        'font-size',
        'font-weight',
      ],
      { unspecified: 'bottomAlphabetical' },
    ],
    'scss/at-rule-no-unknown': [
      true,
      { ignoreAtRules: ['tailwind', 'apply', 'variants', 'responsive', 'screen'] },
    ],
    'at-rule-no-unknown': [
      true,
      { ignoreAtRules: ['tailwind', 'apply', 'variants', 'responsive', 'screen'] },
    ],
  },
  ignoreFiles: ['**/node_modules/**', '**/dist/**'],
};
